version: '3'
services:
  node-app:
    build: .
    ports:
      - "4001:8081"
    links:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart:
      always
